server:
  port: 8080
spring:
  application:
    name: unitrade
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/unitrade?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password: 730948
    lettuce:  # 使用lettuce连接池
      pool:
        max-active: 10  # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10  # 连接池中的最大空闲连接
        min-idle: 1 # 连接池中的最小空闲连接
        time-between-eviction-runs: 10s # 逐出连接的最小空闲时间
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler  # 枚举处理器
  global-config:
    db-config:
      update-strategy: not_null # 更新策略：非空字段才更新
      id-type: auto # 主键策略：自增
  type-aliases-package: com.lantin.unitrade.domain # 别名扫描包
unitrade:
  cart:
    max-items : 10 # 购物车最大商品数量